name:                authie
version:             1.0.0.0
github:              "githubuser/authie"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/authie#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- bcrypt
- monad-logger
- mtl
- persistent
- persistent-postgresql
- persistent-template
- aeson
- servant
- servant-client
- servant-server
- servant-errors
- transformers
- warp
- wai
- wai-cors
- hedis
- containers
- time
- load-env
- envy
- jwt
- SHA
- cookie
- scientific
# - libjwt-typed

library:
  source-dirs: 
  - src

executables:
  authie-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - authie

tests:
  authie-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - authie
