version: '3'
services: 
    database:
        image: "postgres" # use latest official postgres version
        env_file:
        - database.env # configure postgres
        volumes:
        - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
        ports:
        - "127.0.0.1:5432:5432"

    frontend:
        build: ./microservices/frontend
        ports: 
            - "8080:8080"
        volumes: 
            - "./microservices/frontend:/app"
            
    authie:
        build: ./microservices/authie
        ports:
            - "127.0.0.1:8000:8000"
        volumes:
            - "./microservices/authie:/project"
        env_file:
            - "./microservices/authie/.env"
        depends_on:
            - database

    redis:
        image: redis
        container_name: redis-db
        ports:
        - "127.0.0.1:6379:6379"

volumes:
  database-data: # named volumes can be managed easier using docker-compose
