#get node image
FROM node:13.12.0-alpine
#make /app folder in docker
WORKDIR /app
#copy all the dependencies from local to docker and install them
COPY package.json ./
COPY package-lock.json ./

RUN npm install --silent
#cache what is already donwloaded
COPY . .

RUN npm run build

CMD [ "npm", "run", "dev" ]